### ISSUE TITLE
"show desktop" action should not require additional package

### ISSUE THREAD

**Issue by dtcyganok** [janxyz/custom-hot-corners#10]
I am not 100% sure, but I think that the extension can use a already implemented function (showDesktop) from GNOME shell.

**Comment by janxyz** [comment]
I am not aware of such a function in GNOME shell. If you can show me where such function exists and how to call it from Gjs I would be more than happy to remove the wmctrl dependency.

**Comment by dtcyganok** [comment]
"dash-to-panel" extension has "show desktop" functionality and not requires additional packages. I tried to find their implementation, but a quick look did not give any results.

**Comment by janxyz** [comment]
I don't want to reimplement this functionality. Especially not if that implementation would be incompatible with the Gnome hide all normal windows function that is available via key bindings.
