### ISSUE TITLE
Not working after boot

### ISSUE THREAD

**Issue by nmsobri** [janxyz/custom-hot-corners#13]
Hi thank for the extension

I have slight problem.

The extension is working after i installed it,  but it completely not working when i boot my machine..

I need to manually open Gnome Tweak, disable it and then re-enable it to have it working..

Running it on Ubuntu 18.04 ( installed it from gnome extension site )

Please help

**Comment by janxyz** [comment]
Hi, this sounds like a conflict with another extension. You could try to disable all other extensions and see if still not works after booting.

**Comment by mitar** [comment]
Or it might be https://github.com/janxyz/custom-hot-corners/issues/5. I also thought that the extension is not working, but it was just the wrong monitor.

**Comment by piegamesde** [comment]
I can confirm this issue. I also use Dash to Panel.
