### ISSUE TITLE
v0.7 not compatible with gnome-shell 3.36.0 (xorg session)

### ISSUE THREAD

**Issue by liolok** [janxyz/custom-hot-corners#16]
![image](https://user-images.githubusercontent.com/34574198/76220418-6f28b300-6252-11ea-9159-0ccc777b32a1.png)

**Comment by Scotty-Trees** [comment]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by janxyz** [comment]
I've pushed a new commit 71951ef6c9dceab4fd75073f2ea8cdfed2a2d004 to make it work with 3.36 and will also submit a new version to extensions.gnome.org. Sad thing is that now it doesn't work anymore with 3.34. The error I get is `TypeError: GObject.registerClass() used with invalid base class (is HotCorner)`. Not sure if it's possible to make it compatible with both versions.

**Comment by Scotty-Trees** [comment]
> I've pushed a new commit [71951ef](https://github.com/janxyz/custom-hot-corners/commit/71951ef6c9dceab4fd75073f2ea8cdfed2a2d004) to make it work with 3.36 and will also submit a new version to extensions.gnome.org. Sad thing is that now it doesn't work anymore with 3.34. The error I get is `TypeError: GObject.registerClass() used with invalid base class (is HotCorner)`. Not sure if it's possible to make it compatible with both versions.

That's okay, a few other extension creators have mentioned that they can only support the latest version of GNOME, so it's kind of expected on my end.
