### ISSUE TITLE
Fails to install in GNOME Shell 3.35.91

### ISSUE THREAD

**Issue by ricab** [janxyz/custom-hot-corners#17]
The extension fails to install from the [extensions page](https://extensions.gnome.org/extension/1362/custom-hot-corners/) for me. It ends up in ERROR state.

```console
$ gnome-shell --version
GNOME Shell 3.35.91
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
```

I then downloaded version 7 for gnome-shell 3.36 and managed to install with `gnome-extensions install`. I can't get the configuration panel though (nothing happens when clicking it). Should v7 target gnome 3.35 instead?

**Comment by janxyz** [comment]
I just tried to install it from extensions.gnome.org with GNOME Shell 3.36.0 and had no issues. If this only occurs with the development version of GNOME Shell I wouldn't want to invest time in it. For the configuration you could try to run it from the console with `gnome-shell-extension-prefs custom-hot-corners@janrunx.gmail.com` and see if it outputs any errors.

**Comment by ricab** [comment]
Hi, thanks for the reply. I totally understand, I guess it does not make much sense to to spend time for a dev version specifically. I thought it could be a matter of specifying a lower version string, since I got it to run manually here.

Concerning the prefs, yeah there's something fishy with gnome-shell here, does not seem to be a problem with this extension after all.

FWIW, trying the prefs cmd, at first it hang with no output (nor exiting). But I then tried just `gnome-shell-extension-prefs -h` and got the same! Then I started "Extensions" from the Applications screen and it launched, but with nothing inside. De/reactivating, I got the built-in ones to show, but couldn't get settings for any of them. Retrying the commands (passing both custom-hot-corners and just -h) I now get:

```console
$ gnome-shell-extension-prefs -h

(gnome-shell-extension-prefs:94634): Gjs-WARNING **: 16:55:37.364: JS ERROR: Error: Wrong type number; string expected
_updateState@resource:///org/gnome/shell/extensionPrefs/main.js:706:9
_init@resource:///org/gnome/shell/extensionPrefs/main.js:662:9
_addExtensionRow@resource:///org/gnome/shell/extensionPrefs/main.js:423:19
_scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:416:17
asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
main@resource:///org/gnome/shell/extensionPrefs/main.js:762:5
@<main>:1:43
```
