### ISSUE TITLE
For others compiling from source and installing on a clean install of ubuntu 18.04... 

### ISSUE THREAD

**Issue by ThomasKristensen** [janxyz/custom-hot-corners#2]
...I had to do the steps below to get this very nice extension compiled and installed (commit Mar 12, 2018 : commit id 2395bd87301dde0f17b949a0339da84aa513b4a4 ): Tanks a lot to the developer for developing this and sharing the code!
```

sudo apt install autoconf
sudo apt install autopoint
sudo apt-get install libglib2.0-dev
mkdir ~/.local/share/gnome-shell/extensions
```

**Comment by janxyz** [comment]
Thanks for the feedback! I've added a line to the makefile that will create the extension directory if it does not exist. The other steps might be still useful to others so the isssue can stay open.
