### ISSUE TITLE
Bug: The option to require a click in the corner works only on non-maximized windows!

### ISSUE THREAD

**Issue by otgama** [janxyz/custom-hot-corners#26]
Good day.

I'm using Pop!_OS 20.04. Tanks for this extension.

**Comment by otgama** [comment]
In fact, this bug does not happen in the upper left corner

**Comment by G-dH** [comment]
In fact it doesn't work when the corner is covered by any active (focused) window. It's a bug in Gnome code, objects created with a negative scale misbehave. X11 session only. I will fix it.

**Comment by otgama** [comment]
Ok, thanks.

**Comment by G-dH** [comment]
Pull request pending. If you want the fix right now, just replace `extension.js` file from:
[https://github.com/G-dH/custom-hot-corners](https://github.com/G-dH/custom-hot-corners) in:
`~/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/`
directory and restart GS.

You can also test and help to debug my extended version ;)
[https://github.com/G-dH/custom-hot-corners/tree/gdh](https://github.com/G-dH/custom-hot-corners/tree/gdh)

**Comment by otgama** [comment]
Thanks, no more bugs.

How do I Install your extended version?

Sorry man, I don't know how to debug,

**Comment by G-dH** [comment]
@otgama You just helped to debug this extension - used it, found the bug, reported it, tested the fix - perfect, I don't expect more. Thank you.
The installation steps are at the end of the description, but this is not the right place to discuss it...

**Comment by otgama** [comment]
Ok, I found it, thanks.
