### ISSUE TITLE
Fails to work on secondary display

### ISSUE THREAD

**Issue by alanives** [janxyz/custom-hot-corners#29]
Hi, thanks a lot for mantaining the project.

I'd like to report an issue after updating Custom Hot Corners to its 9 version. It still works on my primary display (notebook's screen) but fails to do so on my secondary one.

Please, see below my GNOME Shell and Ubuntu versions, and see attached my extensions screen shot.

```
$ gnome-shell --version
GNOME Shell 3.36.7

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
![Screenshot from 2021-03-30 17-11-23](https://user-images.githubusercontent.com/8486923/113050308-0ffa5100-917b-11eb-8043-faf279d0312f.png)

If you need more information, please, let me know.

Best,
A

**Comment by janxyz** [comment]
Hi, thank you for the bug report. Are you using Wayland or Xorg? You can check this in the Gnome settings under the About menu point.

**Comment by G-dH** [comment]
@alanives  Hi, do you have problem with all corners, or just right and/or bottom corners? X11 or Wayland session? Pointer pressure or clicks? In the last release I've missed a bug in GS 3.36.4 / X11 combination related to a barrier placement but this affect those corners on all monitors. I've fixed this and sent a pull request. Can you please test the fix on your system? Just download `extension.js` file from [https://github.com/G-dH/custom-hot-corners](https://github.com/G-dH/custom-hot-corners), replace the one in `~/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/` and restart Gnome Shell.
Thank you.

**Comment by alanives** [comment]
> Hi, thank you for the bug report. Are you using Wayland or Xorg? You can check this in the Gnome settings under the About menu point.

Hi, @janxyz. Thank you for your reply. I'm using Xorg:

```
$ echo $XDG_SESSION_TYPE
x11
```


> @alanives Hi, do you have problem with all corners, or just right and/or bottom corners? X11 or Wayland session? Pointer pressure or clicks? In the last release I've missed a bug in GS 3.36.4 / X11 combination related to a barrier placement but this affect those corners on all monitors. I've fixed this and sent a pull request. Can you please test the fix on your system? Just download `extension.js` file from https://github.com/G-dH/custom-hot-corners, replace the one in `~/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/` and restart Gnome Shell.
> Thank you.

@G-dH, I'm sorry, I didn't figure out it was only the top right and bottom right corners that were not working; there was some specific direction I should move the cursor to make it work, though. But after replacing the  `extension.js` file this bug has been fixed. :)

Thanks a lot!

**Comment by G-dH** [comment]
@alanives Those parts of the barriers worked 1 px in front of the monitor's edge so the mouse pointer could get behind the barrier missing the trigger.
Thank you for the test!

**Comment by anneris** [comment]
Same issue, came here to find a solution - can confirm the workaround works!
Thanks a lot @G-dH

**Comment by mdcarreira** [comment]
Same for me, this solved my annoying issue of shortcuts being triggered twice!

**Comment by janxyz** [comment]
I've submitted a new version to extensions.gnome.org with the changes made in #30. Please report back if the issue still remains with the new version.
