### ISSUE TITLE
I need to activate the open window.

### ISSUE THREAD

**Issue by iyagicom** [janxyz/custom-hot-corners#3]
For example,
If chromium-browser is enabled, Customcorner should make the active window visible.
If chromium-browser is disabled, Customcorner should open a new one.

These features are essential.
Please make it.

**Comment by janxyz** [comment]
This is possible with a command and wmctrl:

    sh -c 'wmctrl -xa chromium || chromium'

You might need to change the last `chromium` to `chromium-browser` depending on your distribution.

**Comment by iyagicom** [comment]
I installed wmctrl and it worked very well.
Thank you for the tears.
