### ISSUE TITLE
GNOME 40 compatibility

### ISSUE THREAD

**Issue by dtcyganok** [janxyz/custom-hot-corners#31]

**Comment by janxyz** [comment]
I will definitely not have any time for this in the next month so any help is welcome. [Here](https://gjs.guide/extensions/upgrading/gnome-shell-40.html) is nice guide for porting extension to Gnome 40.

**Comment by G-dH** [comment]
I did the basic conversion of my extended version this evening and was surprised that all was usable quite quickly, except for the unscrollable combo box list which contains more than 30 items. And all actions except one work without any change. But under the hood prefs still generates a lot of Gtk warnings..

**Comment by G-dH** [comment]
[Extended version](https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/) with 40+ actions is Gnome 40 compatible already.
