### ISSUE TITLE
Keyboard Shortcuts Needed

### ISSUE THREAD

**Issue by liolok** [janxyz/custom-hot-corners#4]
For now there are `Toggle overview`, `Run command` and `Show desktop` available, I take that as no keyboard shortcuts. Please tell me how to make it through the `Run command` option if I'm wrong.

What I really need is a keyboard shortcut like `Alt + Tab`, to switch in the most recent two windows fast. BTW isn't the `Toggle overview` equals to `Win`/`Super` key?

Anyway, thanks a lot for your work, without this extension there would be no other choices on hot corner stuff.

**Comment by janxyz** [comment]
I'm sorry, currently I don't have any time to test things out but if you don't use Wayland you might be able to do what you want with `Run command` and `xdotool`.

**Comment by liolok** [comment]
@janxyz I see, I'll check on `xdotool` later, thanks again. ❤️

**Comment by liolok** [comment]
After two weeks I finally recalled to google `xdotool alt tab` and found a workaround in ~~[this comment](https://github.com/bulletmark/libinput-gestures/issues/108#issuecomment-334956863)~~ [this answer](https://askubuntu.com/a/122714). For now, it seems just perfect enough to me.
Here is the code for `/home/username/.switchWindow.sh`.
```bash
#!/bin/sh
xdotool keydown alt key Tab; sleep 0.1; xdotool keyup alt
```
And in our extension's config just use `Run Command` and input `/home/username/.switchWindow.sh`.
