### ISSUE TITLE
Primary display should be Window 1

### ISSUE THREAD

**Issue by esplinr** [janxyz/custom-hot-corners#5]
Environment:
* Gnome Shell 3.28.3
* Ubuntu 18.04
* Custom Hot Corners downloaded from extensions.gnome.org for shell version 3.26 version 1

Steps to reproduce:
1. Open Gnome Settings -> Devices -> Displays
2. Verify that the "Built-in display" is the primary display and marked with a "1"
3. Open Gnome Tweaks -> Extensions -> Custom hot corners
4. Setup the top left hot corner on Window 1 to "Toggle overview"
5. Close the setup window and gnome tweaks

Expected behavior:
1. When putting the mouse into the top left corner of the primary display, the overview should be shown

Observed behavior:
1. When putting the mouse in the top left corner of the attached external display, the overview is shown

Notes:
* If the secondary display is unplugged, then the hot corner is correctly displayed on the built-in primary display.
* The gnome extension CustomCorner numbers the displays the same as the Gnome Settings. Perhaps examining their approach will help?
https://gitlab.com/eccheng/customcorner
    const monitor = Main.layoutManager.primaryMonitor;

**Comment by janxyz** [comment]
Thanks for the detailed report. Currently the extension identifies monitors by their position in the Main.layoutManager.monitors array. Although Gnome settings shows the primary display as number 1, the described behavior sounds like the secondary display takes the first place in this array if it is attached. You could verify this with [Looking Glass](https://wiki.gnome.org/Projects/GnomeShell/LookingGlass) by checking the value of `Main.layoutManager.primaryIndex` with the second display attached.

**Comment by esplinr** [comment]
That is the behavior I am seeing. As a result, the hot corner does not behave consistently whereas the approach taken by customcorner is more reliable.

**Comment by WuerfelDev** [comment]
Is it maybe possible to show the vendor and monitor size like its done in gnome-control-center? That would be less confusing

**Comment by janxyz** [comment]
Hi, I'll try to implement that when I find some time for it. Pull requests of course are also welcome.

**Comment by mitar** [comment]
This was completely confusing to me. I thought that the extension does not work.
