### ISSUE TITLE
Just letting you know I created an AUR package.

### ISSUE THREAD

**Issue by ThanosApostolou** [janxyz/custom-hot-corners#6]
Hello, I've created an AUR package here: https://aur.archlinux.org/packages/gnome-shell-extension-custom-hot-corners/. Just letting you know, because it's always a good practice for a downstream maintainer to let the upstream developer know.

BTW, it would be nice if you could do a 0.2 release so that I don't have to create a 2nd git package for the "Applications view" feature.

**Comment by janxyz** [comment]
Thanks for the info. I've now created a 0.2 release for the application view feature.

**Comment by ThanosApostolou** [comment]
Great, thx!
