### ISSUE TITLE
Show desktop no longer works in Gnome 3.32

### ISSUE THREAD

**Issue by IVIbox** [janxyz/custom-hot-corners#7]
Show desktop no longer works in Gnome 3.32, even with wmctrl installed/reinstalled...

**Comment by janxyz** [comment]
Thanks for reporting this. I've fixed this in b9ff02c0e542e46e67fc9570f0094a7bb8edf137 and created a new release. I will upload the new version on extensions.gnome.org as well.

**Comment by IVIbox** [comment]
Thanks for the update you rock!

**Comment by ivandotv** [comment]
Show desktop action doesn't work under Wayland.
Fedora:30
Gnome: 3.32

**Comment by janxyz** [comment]
I've tested it with Gnome 3.32.2 and Arch Linux under Wayland and had no issues. So I am not sure what the reason could be.

**Comment by ivandotv** [comment]
strange, maybe some other extension is interfering. I'll try to narrow down the problem and get back to you.
